version: '2'

services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://root:root@db/trackify_development
    volumes:
      - .:/src/trackify:Z
      - bundler_cache:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "8080:3000"

volumes:
  bundler_cache:
