version: '2'

services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "root"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://root:root@db/trackify_development
    volumes:
      - .:/src/trackify
    depends_on:
      - db
    ports:
      - "8080:3000"
